### ISSUE TITLE
Any way to use this with a Library.XML file?

### ISSUE THREAD

**Issue by BrentEubanks** [mrsilver76/itunes_playlist_exporter#11]
I found this script because I need to recovery my playlists from my iTunes library file.  Thing is, I no longer have iTunes installed - I just have the exported Library.XML.

Is there any way to use this script to parse the playlists out of the XML file, without having iTunes installed?  I don't need the plex functionality - I just need to extract the playlists and update the file path.

I tried hacking on this a bit - I know a little bit of programming but am not savvy of VBS.  I couldn't figure out how to point the script at a text/XML file.  Any ideas/suggestions?

Thanks

**Comment by mrsilver76** [comment]
Hi Brent,

I took a look at the iTunes XML data and it should be reasonably easy to parse it and generate the m3u from that - however it looks like some people have done this already so it might be easier if you tried [this](https://github.com/danielsmith-eu/itunesXMLtoM3U) (command line) or [this](http://www.simav8.com/itunesxmltom3u.html) (graphical interface) instead.

Hope that helps!

**Comment by BrentEubanks** [comment]
Thanks for those links!  I agree that both of those look like viable options. In the meantime, though, I was able to find an old disk image from my OS X media machine, so I was able to export using an OS X tool (https://apps.apple.com/us/app/playlist-export/id434426826?mt=12).
