### ISSUE TITLE
Crashes out when trying to export a playlist with more than 32,767 tracks

### ISSUE THREAD

**Issue by dgparryuk** [mrsilver76/itunes_playlist_exporter#14]
but the fix is really easy, change the two cint to clng
just exported a 75,000 track playlist

**Comment by mrsilver76** [comment]
Ooops, sorry about that and thanks for reporting it. 

I’ve got a couple of other fixes pending so will add this one to the mix.

**Comment by mrsilver76** [comment]
Fixed in 1.7.0. Thanks for reporting this!
