### ISSUE TITLE
Can it work with the new apple Music app, Windows 11

### ISSUE THREAD

**Issue by Hemps38** [mrsilver76/itunes_playlist_exporter#17]
I have it wokring with iTunes and Windows 11, can it work with Apple Music app in windows Store?

**Comment by mrsilver76** [comment]
This script uses the iTunes COM interface to get the details of your playlists. According to [this page](https://developer.apple.com/forums/thread/740837), there appears to be no public API in the Apple Music app.

Unless Apple have a change of heart, I don't think it is going to be possible to get this working with Apple Music.

Sorry 😞
