### ISSUE TITLE
no Windows to Linux path renaming 

### ISSUE THREAD

**Issue by soflane** [mrsilver76/itunes_playlist_exporter#2]
Hey, 

First great script, exactly what i'm looking for. 
I have my iTunes on a Windows machine, and my plex server is on a Linux machine. 
I noticed that the path are not converted to linux, which make the m3u files corrupted, as a result, I see that in my m3u files: 
`/mnt/HDD5/Music/iTunes Media/Music/Brian Tyler\Far Cry 3 (Original Game Soundtrack)\1-01 Far Cry 3.mp3`
instead of what I should get : 
`/mnt/HDD5/Music/iTunes Media/Music/Brian Tyler/Far Cry 3 (Original Game Soundtrack)/1-01 Far Cry 3.mp3`

My question is, are you planning to make a "windows to linux path conversion" feature? 
Thanks in advance

**Comment by mrsilver76** [comment]
Apologies I didn't get the notification that you'd raised an issue. 

Yes I can do that. Leave it with me.

**Comment by mrsilver76** [comment]
Now available in release 1.3.0.
